name: Publish Javadoc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build documentationSite

      - name: Create Javadoc artifact
        id: deployment
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy Javadoc to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
